services:
  mongodb:
    image: mongo:7
    container_name: lefteria-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lefteriafc-backend:latest
    container_name: lefteria-backend
    restart: always
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=lefteria_fc
      - CORS_ORIGINS=*
      - JWT_SECRET=6c4d1d20b58640298b2756ca624534372bd696aa08eee1adb6392c3588b3c722
      - ADMIN_USERNAME=Lefteria FC
      - ADMIN_PASSWORD=L3ft3r1@FC#2024$$Secure!
      - VAPID_PUBLIC_KEY=BKSDwwWVyapiWEVJ6vgeqaWJvmYSeLcdJG0jEioOfXGBkCwlHV7pn3d_r0OzXJLtXPeYxhEHRTkjjrG1s528jLg
      - VAPID_PRIVATE_KEY=MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgAPCgJdxsY9Jz2Q3D1C6CsnEFyfypWaFSlHZd2NaSAfihRANCAASkg8MFlcmqYlhFSer4Hqmlib5mEni3HSRtIxIqDn1xgZAsJR1e6Z93f69Ds1yS7Vz3mMYRB0U5I46xtbOdvIy4
      - VAPID_CONTACT=mailto:info@lefteriafc.cy
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://195.35.1.58
        - REACT_APP_VAPID_PUBLIC_KEY=BKSDwwWVyapiWEVJ6vgeqaWJvmYSeLcdJG0jEioOfXGBkCwlHV7pn3d_r0OzXJLtXPeYxhEHRTkjjrG1s528jLg
    image: lefteriafc-frontend:latest
    container_name: lefteria-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  uploads_data:
